name: Full intergation workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Log in to the Container registry
              uses: docker/login-action@v3.0.0
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
              
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              
            - name: Set up Docker Compose  
              uses: docker/setup-compose-action@v1
              
            - name: Build and push with Buildx via Compose
              run: |
                # Используем buildx через DOCKER_BUILDKIT
                DOCKER_BUILDKIT=1 docker compose build
                docker compose push
    release:
      needs: build-and-push
      runs-on: ubuntu-latest
      permissions:
        issues: write
        contents: write
        pull-requests: write
        
      steps:
        - name: Release
          uses: googleapis/release-please-action@v4
          with:
            # this assumes that you have created a personal access token
            # (PAT) and configured it as a GitHub action secret named
            token: ${{ secrets.GITHUB_TOKEN }}
            # this is a built-in strategy in release-please, see "Action Inputs"
            # for more options
            release-type: simple
